/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javadatabase;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;


/**
 *
 * @author imadw
 */
public class MainFrame extends javax.swing.JFrame {

    private int rowEdit = -1;
    DefaultTableModel modelMahasiswa;
    boolean isEdit;
    private int editRowIndex;
    private Object txtfNama;
    
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;
    
    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Kuliahku";
    String user = "postgres";
    String password = "03062004";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        cmbJenisMahasiswa.removeAllItems();
        cmbJenisMahasiswa.addItem("Reguler");
        cmbJenisMahasiswa.addItem("Beasiswa");
        cmbJenisMahasiswa.addItem("Internasional");
        
        tblMahasiswa.addMouseListener(new MouseAdapter() {
        public void mouseClicked(MouseEvent evt) {
            int row = tblMahasiswa.getSelectedRow();
            txtNim.setText(modelMahasiswa.getValueAt(row, 0).toString());
            txtNama.setText(modelMahasiswa.getValueAt(row, 1).toString());
            cmbJenisMahasiswa.setSelectedItem(
            modelMahasiswa.getValueAt(row, 3).toString());
            txtJumlahSks.setText(
            modelMahasiswa.getValueAt(row, 4).toString());

        }
    });
        
        String[] kolom = {"nim", "nama", "tahunmasuk", "jenismahasiswa", "jumlahsks", "biayakuliah"};
        modelMahasiswa = new DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(modelMahasiswa);
        int row = tblMahasiswa.getSelectedRow();
        

        loadData();
    }
    
    private void insert() {}

     private void loadData() {
        modelMahasiswa.setRowCount(0);
        int no = 1;

    try {
        Class.forName(driver);
        conn = DriverManager.getConnection(koneksi, user, password);

        String sql = "SELECT nim, nama, tahunmasuk, jenismahasiswa, jumlahsks, biayakuliah FROM public.\"Mahasiswa\"";
        stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        DecimalFormatSymbols symbols = new DecimalFormatSymbols(new Locale("id","ID"));
        symbols.setGroupingSeparator('.');
        symbols.setDecimalSeparator(',');

        DecimalFormat df = new DecimalFormat("#,##0.00", symbols);

        // ✅ HANYA SATU while
        while (rs.next()) {
            Object[] data = {
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getInt("tahunmasuk"),
                rs.getString("jenismahasiswa"),
                rs.getInt("jumlahsks"),
                df.format(rs.getDouble("biayakuliah")) // 2 desimal
            };
            modelMahasiswa.addRow(data);
        }

        rs.close();
        stmt.close();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lblMahasiswa = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        btnUpload = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cmbJenisMahasiswa = new javax.swing.JComboBox<>();
        lblJenisMahasiswa = new javax.swing.JLabel();
        lblSks = new javax.swing.JLabel();
        txtJumlahSks = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        lblMahasiswa.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        lblMahasiswa.setText("MAHASISWA");

        lblNama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNama.setText("Masukkan Nama");

        lblNim.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNim.setText("Masukkan Nim");

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNimActionPerformed(evt);
            }
        });

        btnUpload.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnTambah.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        cmbJenisMahasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbJenisMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisMahasiswaActionPerformed(evt);
            }
        });

        lblJenisMahasiswa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblJenisMahasiswa.setText("Jenis Mahasiswa");

        lblSks.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSks.setText("Jumlah SKS");

        txtJumlahSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSksActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(tblMahasiswa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMahasiswa)
                .addGap(259, 259, 259))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(lblNim)
                            .addComponent(lblJenisMahasiswa)
                            .addComponent(lblSks))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNim)
                                .addComponent(cmbJenisMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING, 0, 343, Short.MAX_VALUE)
                                .addComponent(txtJumlahSks, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUpload)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblMahasiswa)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNim)
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJenisMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblJenisMahasiswa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJumlahSks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSks))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpload)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNimActionPerformed

    private void cmbJenisMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisMahasiswaActionPerformed
         
    }//GEN-LAST:event_cmbJenisMahasiswaActionPerformed

    private void txtJumlahSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSksActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
                                    
    JFileChooser chooser = new JFileChooser();
    if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        return;
    }

    File file = chooser.getSelectedFile();

    try (
        BufferedReader br = new BufferedReader(new FileReader(file))
    ) {
        Class.forName(driver);
        conn = DriverManager.getConnection(koneksi, user, password);

        String line;
        while ((line = br.readLine()) != null) {

            // Skip baris kosong
            if (line.trim().isEmpty()) continue;

            String[] d = line.split(",");

            // Validasi jumlah kolom CSV
            if (d.length != 5) {
                JOptionPane.showMessageDialog(
                    this,
                    "Format CSV salah!\nGunakan: nim,nama,tahunmasuk,jenismahasiswa,jumlahsks"
                );
                return;
            }

            String nim = d[0].trim();
            String nama = d[1].trim();
            int tahunmasuk = Integer.parseInt(d[2].trim());
            String jenis = d[3].trim();
            int jumlahsks = Integer.parseInt(d[4].trim());

            // =======================
            // HITUNG BIAYA (OOP)
            // =======================
            Mahasiswa m;
            if (jenis.equalsIgnoreCase("Reguler")) {
                m = new Reguler(0, nim, nama, tahunmasuk, jumlahsks);
            } else if (jenis.equalsIgnoreCase("Beasiswa")) {
                m = new Beasiswa(0, nim, nama, tahunmasuk, jumlahsks);
            } else {
                m = new Internasional(0, nim, nama, tahunmasuk, jumlahsks);
            }

            m.hitungBiaya();
            double biayakuliah = m.getbiayakuliah();

            // =======================
            // INSERT DATABASE
            // =======================
            String sql = "INSERT INTO public.\"Mahasiswa\" "
                       + "(nim, nama, tahunmasuk, jenismahasiswa, jumlahsks, biayakuliah) "
                       + "VALUES (?,?,?,?,?,?)";

            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);
            pstmt.setString(2, nama);
            pstmt.setInt(3, tahunmasuk);
            pstmt.setString(4, jenis);
            pstmt.setInt(5, jumlahsks);
            pstmt.setDouble(6, biayakuliah);
            pstmt.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Upload CSV berhasil!");
        loadData();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error upload: " + e.getMessage());
    } finally {
        try {
            if (pstmt != null) pstmt.close();
            if (conn != null) conn.close();
        } catch (Exception ex) {
            // abaikan
        }
    }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
        return;
        }

        String nim = modelMahasiswa.getValueAt(row, 0).toString();
        String nama = txtNama.getText().trim();
        String sksText = txtJumlahSks.getText().trim();
        String jenis = cmbJenisMahasiswa.getSelectedItem().toString();

        if (nama.isEmpty() || sksText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama dan SKS tidak boleh kosong!");
        return;
        }

        int sks;
        try {
            sks = Integer.parseInt(sksText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "SKS harus berupa angka!");
            return;
        }

    try {
        Class.forName(driver);
        conn = DriverManager.getConnection(koneksi, user, password);

        String sql = "UPDATE public.\"Mahasiswa\" "
                   + "SET nama=?, jenismahasiswa=?, jumlahsks=? "
                   + "WHERE nim=?";

        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nama);
        pstmt.setString(2, jenis);
        pstmt.setInt(3, sks);
        pstmt.setString(4, nim);
        pstmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
        loadData();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String nim = txtNim.getText().trim();
        String nama = txtNama.getText().trim();
        String jenis = cmbJenisMahasiswa.getSelectedItem().toString();
        String sksText = txtJumlahSks.getText().trim();
        int tahunmasuk = 2024;

    // ✅ VALIDASI INPUT
    if (nim.isEmpty() || nama.isEmpty() || sksText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
        return;
    }

    int jumlahsks;
    try {
        jumlahsks = Integer.parseInt(sksText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah SKS harus angka!");
        return;
    }

    try {
        // ✅ BUAT OBJEK SESUAI JENIS
        Mahasiswa m;
        if (jenis.equals("Reguler")) {
            m = new Reguler(0, nim, nama, tahunmasuk, jumlahsks);
        } else if (jenis.equals("Beasiswa")) {
            m = new Beasiswa(0, nim, nama, tahunmasuk, jumlahsks);
        } else {
            m = new Internasional(0, nim, nama, tahunmasuk, jumlahsks);
        }

        m.hitungBiaya();
        double biayakuliah = m.getbiayakuliah();

        // ✅ KONEKSI DATABASE
        Class.forName(driver);
        conn = DriverManager.getConnection(koneksi, user, password);

        String sql = "INSERT INTO public.\"Mahasiswa\" "
                   + "(nim, nama, tahunmasuk, jenismahasiswa, jumlahsks, biayakuliah) "
                   + "VALUES (?,?,?,?,?,?)";

        pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nim);
        pstmt.setString(2, nama);
        pstmt.setInt(3, tahunmasuk);
        pstmt.setString(4, jenis);
        pstmt.setInt(5, jumlahsks);
        pstmt.setDouble(6, biayakuliah);

        pstmt.executeUpdate();
        conn.close();

        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
        loadData();

        // optional: bersihkan input
        txtNim.setText("");
        txtNama.setText("");
        txtJumlahSks.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menambah data: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
            return;
        }

        String nim = modelMahasiswa.getValueAt(row, 0).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin hapus NIM " + nim + "?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            String sql = "DELETE FROM public.\"Mahasiswa\" WHERE nim=?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            loadData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbJenisMahasiswa;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJenisMahasiswa;
    private javax.swing.JLabel lblMahasiswa;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JLabel lblSks;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtJumlahSks;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables

}