/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaDatabase;

import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imadw
 */
public class MainFrame extends javax.swing.JFrame {

    private int rowEdit = -1;
    DefaultTableModel modelMahasiswa;
    boolean isEdit;
    private int editRowIndex;
    private Object txtfNama;
    
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;
    
    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Kuliah";
    String user = "postgres";
    String password = "12345678";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        String[] kolom = {"Nama", "NIM"};
        modelMahasiswa = new DefaultTableModel(kolom, 0);
        tblMahasiswa.setModel(modelMahasiswa);
        isEdit = false;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        lblMahasiswa = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblNim = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNim = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnUpload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMahasiswa.setText("Mahasiswa");

        lblNama.setText("Masukkan Nama");

        lblNim.setText("Masukkan Nim");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMahasiswa);

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpload)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNim, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNama, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama)
                            .addComponent(txtNim))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMahasiswa)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMahasiswa)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNim)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah)
                    .addComponent(btnUpload))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String nim = txtNim.getText().trim();
        String nama = txtNama.getText().trim();
        int angkatan = 2024;

        if (nim.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "NIM dan Nama harus diisi!");
            return;
        }

        try {
            // Pastikan driver tersedia
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            if (isEdit) {
                String sql = "UPDATE public.\"Mahasiswa\" SET \"nama\" = ?, \"tahunmasuk\" = ? WHERE \"nim\" = ?";
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(3, nim);
                pstmt.setString(1, nama);
                pstmt.setInt(2, angkatan);
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                isEdit = false;
            } else {
                String sql = "INSERT INTO public.\"Mahasiswa\" (\"nim\", \"nama\", \"tahunmasuk\") VALUES (?, ?, ?)";
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(1, nim);
                pstmt.setString(2, nama);
                pstmt.setInt(3, angkatan);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            }

            // tampilkan ke tabel GUI 
            Object[] dataBaru = {nama, nim, angkatan};
            modelMahasiswa.addRow(dataBaru);

            txtNim.setText("");
            txtNama.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace(); // tambahkan ini biar tahu detail error di console
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }                                          
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int editRow = tblMahasiswa.getSelectedRow();
        if (editRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit terlebih dahulu!");
            return;
        }

        // Ambil data dari baris yang dipilih
        String namaLama = (String) tblMahasiswa.getValueAt(editRow, 0);
        String nim = (String) tblMahasiswa.getValueAt(editRow, 1);

        // Minta input baru dari user (bisa juga langsung dari text field)
        String namaBaru = JOptionPane.showInputDialog(this,
                "Edit nama mahasiswa:", namaLama);

        if (namaBaru == null || namaBaru.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }

        int tahunMasuk = 2025; // misalnya fix, atau bisa kamu ubah sesuai kebutuhan

        // --- koneksi database dan update ---
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            String sql = "UPDATE public.\"Mahasiswa\" SET \"nama\" = ?, \"tahunmasuk\" = ? WHERE \"nim\" = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, namaBaru);
            pstmt.setInt(2, tahunMasuk);
            pstmt.setString(3, nim);

            int updated = pstmt.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                // perbarui juga tabel GUI
                modelMahasiswa.setValueAt(namaBaru, editRow, 0);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diperbarui (NIM tidak ditemukan)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }                                       

    private void insert() {

    }

    private void loadData() {
        //select * from mahasiswa    // Hapus dulu semua data di tabel GUI sebelum memuat ulang
        modelMahasiswa.setRowCount(0);

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            // Query ambil semua data
            String sql = "SELECT \"nim\", \"nama\", \"tahunmasuk\" FROM public.\"Mahasiswa\"";
            ResultSet rs = stmt.executeQuery(sql);

            // Loop hasil query dan masukkan ke model tabel
            while (rs.next()) {
                String nim = rs.getString("nim");
                String nama = rs.getString("nama");
                int tahunMasuk = rs.getInt("tahunmasuk");

                Object[] data = {nama, nim, tahunMasuk};
                modelMahasiswa.addRow(data);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMahasiswa.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus terlebih dahulu!");
            return;
        }

        // Ambil data dari tabel
        String nim = (String) tblMahasiswa.getValueAt(selectedRow, 1);

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah kamu yakin ingin menghapus data dengan NIM: " + nim + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Koneksi ke database
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            // SQL DELETE
            String sql = "DELETE FROM public.\"Mahasiswa\" WHERE \"nim\" = ?";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nim);

            int deleted = pstmt.executeUpdate();

            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus dari database!");
                // Hapus juga dari tabel GUI
                modelMahasiswa.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus! NIM tidak ditemukan di database.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) {
                    pstmt.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        // Pilih file CSV dari komputer
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = chooser.getSelectedFile();

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;

            // Lewati header CSV
            //br.readLine();

            int sukses = 0;
            int gagal = 0;

            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] data = line.split(",");

                if (data.length < 3) {
                    gagal++;
                    continue;
                }

                String nim = data[0].trim();
                String nama = data[1].trim();
                int tahun = Integer.parseInt(data[2].trim());

                try {
                    String sql = "INSERT INTO public.\"Mahasiswa\" (\"nim\", \"nama\", \"tahunmasuk\") VALUES (?, ?, ?)";

                    pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, nim);
                    pstmt.setString(2, nama);
                    pstmt.setInt(3, tahun);
                    pstmt.executeUpdate();

                    // Masukkan ke tabel GUI
                    Object[] row = {nama, nim, tahun};
                    modelMahasiswa.addRow(row);

                    sukses++;
                } catch (SQLException ex) {
                    gagal++;
                }
            }

            br.close();

            JOptionPane.showMessageDialog(this,
                    "Upload selesai!\nSukses: " + sukses + "\nGagal: " + gagal);
            loadData();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpload;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMahasiswa;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNim;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables

}